export { default as DashboardPage } from "./DashboardPage";
export { default as EmergencyPage } from "./EmergencyPage";
export { default as InformationPage } from "./InformationPage";
export { default as ManagementPage } from "./ManagementPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as SettingsPage } from "./SettingsPage";
export { default as MapPage } from "./MapPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as LoginPage } from "./LoginPage";
